const employee = [
  {
    name: "John Doe",
    id: 1,
    email: "john.doe@example.com",
    password: "password123",
    taskCount: {
      active: 1,
      new: 1,
      completed: 1,
      failed: 1
    },
    tasks: [
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Complete project report",
        description: "Finish the quarterly project report",
        date: "2023-06-15",
        category: "Reporting",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Client meeting",
        description: "Prepare and attend client meeting",
        date: "2023-06-18",
        category: "Client Relations",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Training session",
        description: "Attend team training session",
        date: "2023-06-10",
        category: "Professional Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Code review",
        description: "Review pull requests for the new feature",
        date: "2023-06-20",
        category: "Development",
      },
    ],
  },
  {
    name: "Jane Smith",
    id: 2,
    email: "jane.smith@example.com",
    password: "password123",
    taskCount: {
      active: 2,
      new: 1,
      completed: 1,
      failed: 1
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Design new UI",
        description: "Create mockups for the new user interface",
        date: "2023-06-17",
        category: "Design",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Bug fix",
        description: "Fix critical bug in production",
        date: "2023-06-12",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Team meeting",
        description: "Attend weekly team sync",
        date: "2023-06-19",
        category: "Team Management",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Documentation",
        description: "Update API documentation",
        date: "2023-06-22",
        category: "Documentation",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Performance review",
        description: "Complete self-assessment for performance review",
        date: "2023-06-08",
        category: "HR",
      },
    ],
  },
  {
    name: "Alice Johnson",
    id: 3,
    email: "alice.johnson@example.com",
    password: "password123",
    taskCount: {
      active: 1,
      new: 1,
      completed: 1,
      failed: 0
    },
    tasks: [
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Data analysis",
        description: "Analyze customer data for insights",
        date: "2023-06-16",
        category: "Analytics",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Presentation prep",
        description: "Prepare slides for board meeting",
        date: "2023-06-21",
        category: "Management",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Budget review",
        description: "Review and approve department budget",
        date: "2023-06-09",
        category: "Finance",
      },
    ],
  },
  {
    name: "Bob Brown",
    id: 4,
    email: "bob.brown@example.com",
    password: "password123",
    taskCount: {
      active: 2,
      new: 2,
      completed: 1,
      failed: 1
    },
    tasks: [
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Server maintenance",
        description: "Perform routine server maintenance",
        date: "2023-06-18",
        category: "IT",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Security audit",
        description: "Conduct security audit of systems",
        date: "2023-06-23",
        category: "Security",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Software update",
        description: "Roll out software update to all departments",
        date: "2023-06-11",
        category: "IT",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Backup check",
        description: "Verify integrity of backup systems",
        date: "2023-06-20",
        category: "IT",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "New hire setup",
        description: "Set up workstation for new employee",
        date: "2023-06-07",
        category: "IT",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Network optimization",
        description: "Optimize network performance",
        date: "2023-06-25",
        category: "IT",
      },
    ],
  },
  {
    name: "Charlie Davis",
    id: 5,
    email: "charlie.davis@example.com",
    password: "password123",
    taskCount: {
      active: 2,
      new: 2,
      completed: 2,
      failed: 1
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Marketing campaign",
        description: "Launch new product marketing campaign",
        date: "2023-06-19",
        category: "Marketing",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Social media strategy",
        description: "Develop Q3 social media strategy",
        date: "2023-06-24",
        category: "Marketing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Press release",
        description: "Write press release for new product launch",
        date: "2023-06-10",
        category: "PR",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Customer survey",
        description: "Prepare and send out customer satisfaction survey",
        date: "2023-06-22",
        category: "Customer Relations",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Vendor negotiation",
        description: "Negotiate new terms with advertising vendor",
        date: "2023-06-13",
        category: "Procurement",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        title: "Event planning",
        description: "Plan company summer event",
        date: "2023-06-28",
        category: "HR",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Budget allocation",
        description: "Allocate marketing budget for Q3",
        date: "2023-06-26",
        category: "Finance",
      },
    ],
  },
];

const admin = [
  {
    name: "Admin One",
    id: 1,
    email: "admin.one@example.com",
    password: "adminpassword",
  },
  {
    name: "Admin Two",
    id: 2,
    email: "admin.two@example.com",
    password: "adminpassword",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employee));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employeeData = JSON.parse(localStorage.getItem("employees"));
  const adminData = JSON.parse(localStorage.getItem("admin"));
  return { employeeData, adminData };
};
